name: Linting and style checking

on: [push, pull_request]

jobs:
  Luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup tools
        run: |
          sudo apt install -y luarocks
          sudo luarocks install luacheck
      - name: Lint
        run: make lint

  Stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua/
